"""Dev-only generator: bakes a static country table into travel_viewer/countries.py.

Uses pycountry (names, alpha-3) + pycountry_convert (continent) at build time so the
app itself has no dependency on either. Re-run only if the sovereign-state list changes.
"""

import subprocess
from pathlib import Path

import pycountry
import pycountry_convert as pcc

# The 195 sovereign states: 193 UN members + Vatican City + Palestine.
# Curated by hand because ISO 3166-1 has 249 entries and does not mark sovereignty.
UN_195 = """
AF AL DZ AD AO AG AR AM AU AT AZ BS BH BD BB BY BE BZ BJ BT BO BA BW BR BN BG BF BI
CV KH CM CA CF TD CL CN CO KM CG CD CR CI HR CU CY CZ DK DJ DM DO EC EG SV GQ ER EE
SZ ET FJ FI FR GA GM GE DE GH GR GD GT GN GW GY HT VA HN HU IS IN ID IR IQ IE IL IT
JM JP JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MG MW MY MV ML MT MH MR MU
MX FM MD MC MN ME MA MZ MM NA NR NP NL NZ NI NE NG MK NO OM PK PW PS PA PG PY PE PH PL
PT QA RO RU RW KN LC VC WS SM ST SA SN RS SC SL SG SK SI SB SO ZA SS ES LK SD SR SE
CH SY TJ TZ TH TL TG TO TT TN TR TM TV UG UA AE GB US UY UZ VU VE VN YE ZM ZW
""".split()

# Short display names where the ISO name is unwieldy on a chip.
SHORT_NAMES = {
    "BO": "Bolivia",
    "BN": "Brunei",
    "CD": "DR Congo",
    "CG": "Congo",
    "CI": "Cote d'Ivoire",
    "CZ": "Czechia",
    "FM": "Micronesia",
    "GB": "United Kingdom",
    "IR": "Iran",
    "KP": "North Korea",
    "KR": "South Korea",
    "LA": "Laos",
    "MD": "Moldova",
    "PS": "Palestine",
    "RU": "Russia",
    "SY": "Syria",
    "TR": "Turkiye",
    "TZ": "Tanzania",
    "US": "United States",
    "VA": "Vatican City",
    "VE": "Venezuela",
    "VN": "Vietnam",
}

CONTINENT_NAMES = {
    "AF": "Africa",
    "AS": "Asia",
    "EU": "Europe",
    "NA": "Americas",
    "SA": "Americas",
    "OC": "Oceania",
}

# pycountry_convert has no mapping for these.
CONTINENT_OVERRIDES = {"VA": "Europe", "TL": "Asia", "PS": "Asia"}


def main() -> None:
    assert len(UN_195) == 195, f"expected 195 codes, got {len(UN_195)}"
    assert len(set(UN_195)) == 195, "duplicate codes in list"

    rows = []
    for alpha2 in sorted(UN_195):
        country = pycountry.countries.get(alpha_2=alpha2)
        assert country is not None, f"unknown alpha-2: {alpha2}"

        # common_name is only present on some records (e.g. "Bolivia" vs the long
        # official name), so reach for it defensively.
        name = SHORT_NAMES.get(alpha2) or getattr(country, "common_name", None) or country.name

        if alpha2 in CONTINENT_OVERRIDES:
            region = CONTINENT_OVERRIDES[alpha2]
        else:
            region = CONTINENT_NAMES[pcc.country_alpha2_to_continent_code(alpha2)]

        rows.append((alpha2, country.alpha_3, name, region))

    lines = [
        '"""Static reference data for the 195 sovereign states.',
        "",
        "Generated by scripts/gen_countries.py - do not edit by hand.",
        '"""',
        "",
        "from typing import NamedTuple",
        "",
        "",
        "class Country(NamedTuple):",
        '    """One sovereign state, keyed by ISO 3166-1 alpha-2."""',
        "",
        "    alpha2: str",
        "    alpha3: str",
        "    name: str",
        "    region: str",
        "",
        "",
        "COUNTRIES: tuple[Country, ...] = (",
    ]
    for alpha2, alpha3, name, region in rows:
        lines.append(f'    Country("{alpha2}", "{alpha3}", {name!r}, "{region}"),')
    lines += [
        ")",
        "",
        'REGIONS: tuple[str, ...] = ("Europe", "Asia", "Africa", "Americas", "Oceania")',
        "",
        "BY_ALPHA2: dict[str, Country] = {c.alpha2: c for c in COUNTRIES}",
        "",
    ]

    out = Path(__file__).resolve().parent.parent / "travel_viewer" / "countries.py"
    text = "\n".join(lines)
    non_ascii = sorted({ch for ch in text if ord(ch) > 127})
    assert not non_ascii, f"non-ASCII in output, add a SHORT_NAMES entry: {non_ascii}"
    out.write_text(text, encoding="utf-8", newline="\n")

    # Emit canonical formatting so the generated file passes `ruff format --check`.
    subprocess.run(["ruff", "format", "--quiet", str(out)], check=True)

    counts: dict[str, int] = {}
    for _, _, _, region in rows:
        counts[region] = counts.get(region, 0) + 1
    print(f"wrote {len(rows)} countries to {out}")
    print("per region:", counts)


if __name__ == "__main__":
    main()
